var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var schema_exports = {};
__export(schema_exports, {
  addSchema: () => addSchema,
  deleteSchema: () => deleteSchema,
  generateDataModule: () => generateDataModule,
  generateMigration: () => generateMigration,
  loadSchemas: () => loadSchemas,
  saveSchemas: () => saveSchemas
});
module.exports = __toCommonJS(schema_exports);
var import_fs = require("fs");
var import_path = require("path");
var import_sandbox = require("../file/sandbox");
function getSchemaPath(projectPath) {
  return (0, import_path.join)(projectPath, ".luano", "datastore-schemas.json");
}
function loadSchemas(projectPath) {
  const path = getSchemaPath(projectPath);
  if (!(0, import_fs.existsSync)(path)) {
    return { schemas: [], createdAt: (/* @__PURE__ */ new Date()).toISOString(), updatedAt: (/* @__PURE__ */ new Date()).toISOString() };
  }
  try {
    return JSON.parse((0, import_fs.readFileSync)(path, "utf-8"));
  } catch {
    return { schemas: [], createdAt: (/* @__PURE__ */ new Date()).toISOString(), updatedAt: (/* @__PURE__ */ new Date()).toISOString() };
  }
}
function saveSchemas(projectPath, file) {
  (0, import_sandbox.ensureLuanoDir)(projectPath);
  file.updatedAt = (/* @__PURE__ */ new Date()).toISOString();
  (0, import_fs.writeFileSync)(getSchemaPath(projectPath), JSON.stringify(file, null, 2), "utf-8");
}
function addSchema(projectPath, schema) {
  const file = loadSchemas(projectPath);
  const existing = file.schemas.findIndex((s) => s.name === schema.name);
  if (existing >= 0) {
    file.schemas[existing] = schema;
  } else {
    file.schemas.push(schema);
  }
  saveSchemas(projectPath, file);
  return file;
}
function deleteSchema(projectPath, name) {
  const file = loadSchemas(projectPath);
  file.schemas = file.schemas.filter((s) => s.name !== name);
  saveSchemas(projectPath, file);
  return file;
}
function luauDefault(field) {
  if (field.default === null || field.default === void 0) {
    switch (field.type) {
      case "string":
        return '""';
      case "number":
        return "0";
      case "boolean":
        return "false";
      case "table":
        return "{}";
      case "array":
        return "{}";
      case "Vector3":
        return "Vector3.new(0, 0, 0)";
      case "Color3":
        return "Color3.new(1, 1, 1)";
      case "CFrame":
        return "CFrame.new()";
      default:
        return "nil";
    }
  }
  if (typeof field.default === "string") return `"${field.default}"`;
  if (typeof field.default === "boolean") return field.default ? "true" : "false";
  return String(field.default);
}
function generateFieldTemplate(fields, indent) {
  const pad = "	".repeat(indent);
  const lines = [];
  for (const f of fields) {
    const comment = f.description ? ` -- ${f.description}` : "";
    if (f.type === "table" && f.children?.length) {
      lines.push(`${pad}${f.name} = {${comment}`);
      lines.push(generateFieldTemplate(f.children, indent + 1));
      lines.push(`${pad}},`);
    } else {
      lines.push(`${pad}${f.name} = ${luauDefault(f)},${comment}`);
    }
  }
  return lines.join("\n");
}
function generateDataModule(schema) {
  const template = generateFieldTemplate(schema.fields, 2);
  const name = schema.name;
  return `--!strict
-- Auto-generated by Luano DataStore Designer
-- Schema: ${name} v${schema.version}
-- Generated at ${(/* @__PURE__ */ new Date()).toISOString()}

local DataStoreService = game:GetService("DataStoreService")
local HttpService = game:GetService("HttpService")
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

local ${name} = {}
${name}.__index = ${name}

local DATA_STORE_NAME = "${name}"
local DATA_VERSION = ${schema.version}

-- Session takeover threshold. If another server's heartbeat is older than this,
-- we assume that server crashed without releasing the lock and take over.
local SESSION_STALE_SEC = 30 * 60
-- Roblox DataStore size limit is 4 MB serialized. We leave a 1 KB safety margin
-- so a save that's right at the edge doesn't fail because of session metadata.
local MAX_SIZE_BYTES = 4 * 1024 * 1024 - 1024
-- Heartbeat interval. The auto-save loop also acts as the lock heartbeat \u2014 every
-- save updates _session.lastSeen so other servers know we're still alive.
local HEARTBEAT_INTERVAL = 60

local store = DataStoreService:GetDataStore(DATA_STORE_NAME)

-- Tracks which players this server holds session locks for. Module-level so a
-- single game:BindToClose can flush every active session before shutdown.
local activeSessions: { [Player]: { data: { [string]: any }, sessionId: string } } = {}

-- \u2500\u2500 Internal helpers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

local function deepMerge(target: { [string]: any }, source: { [string]: any }): { [string]: any }
	for k, v in source do
		if target[k] == nil then
			target[k] = if type(v) == "table" then table.clone(v) else v
		elseif type(v) == "table" and type(target[k]) == "table" then
			deepMerge(target[k], v)
		end
	end
	return target
end

local function withinSizeLimit(data: any): (boolean, string?)
	local ok, encoded = pcall(function() return HttpService:JSONEncode(data) end)
	if not ok then return false, "JSON encode failed" end
	if #encoded > MAX_SIZE_BYTES then
		return false, string.format("Data is %d bytes (limit %d)", #encoded, MAX_SIZE_BYTES)
	end
	return true, nil
end

-- \u2500\u2500 Template \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

function ${name}.getTemplate(): { [string]: any }
	return {
		_version = DATA_VERSION,
${template}
	}
end

-- \u2500\u2500 Migration \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
-- Recursive merge: any field present in the template but missing from data
-- (including nested table fields) gets filled with the default. Existing values
-- are preserved untouched. _fromVersion is unused by the default merge but is
-- kept in the signature so projects can hook custom step migrations on top.

function ${name}.migrate(data: { [string]: any }, _fromVersion: number): { [string]: any }
	deepMerge(data, ${name}.getTemplate())
	data._version = DATA_VERSION
	return data
end

-- \u2500\u2500 Load (atomic, with session lock) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
-- Uses UpdateAsync so the read + lock + write happens in one transaction.
-- Returns (data, sessionId) on success. Returns (nil, reason) on failure.
-- Pass the returned sessionId to save() and unlock().

function ${name}.load(player: Player): ({ [string]: any }?, string?)
	local key = "player_" .. player.UserId
	local sessionId = HttpService:GenerateGUID(false)
	local now = os.time()
	local locked = false

	local ok, result = pcall(function()
		return store:UpdateAsync(key, function(existing)
			if existing and existing._session then
				local age = now - (existing._session.lastSeen or 0)
				if existing._session.id ~= sessionId and age < SESSION_STALE_SEC then
					locked = true
					return nil
				end
			end
			existing = existing or ${name}.getTemplate()
			if (existing._version or 0) < DATA_VERSION then
				existing = ${name}.migrate(existing, existing._version or 0)
			end
			existing._session = { id = sessionId, lastSeen = now }
			return existing
		end)
	end)

	if not ok then
		warn("[${name}] Load failed for " .. player.Name .. ": " .. tostring(result))
		return nil, "Load failed: " .. tostring(result)
	end
	if locked then
		return nil, "Session active in another server"
	end
	return result, sessionId
end

-- \u2500\u2500 Save (atomic, session-checked, size-guarded) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

function ${name}.save(player: Player, data: { [string]: any }, sessionId: string): boolean
	local sizeOk, sizeErr = withinSizeLimit(data)
	if not sizeOk then
		warn("[${name}] " .. player.Name .. ": " .. tostring(sizeErr))
		return false
	end

	local key = "player_" .. player.UserId
	local now = os.time()
	local mismatch = false

	local ok, err = pcall(function()
		return store:UpdateAsync(key, function(existing)
			if existing and existing._session and existing._session.id ~= sessionId then
				mismatch = true
				return nil
			end
			data._session = { id = sessionId, lastSeen = now }
			return data
		end)
	end)

	if not ok then
		warn("[${name}] Save failed for " .. player.Name .. ": " .. tostring(err))
		return false
	end
	if mismatch then
		warn("[${name}] Session mismatch for " .. player.Name .. " \u2014 another server holds the lock")
		return false
	end
	return true
end

-- \u2500\u2500 Unlock (call when player leaves so another server can take over fast) \u2500\u2500\u2500

function ${name}.unlock(player: Player, sessionId: string): boolean
	local key = "player_" .. player.UserId
	local ok = pcall(function()
		store:UpdateAsync(key, function(existing)
			if existing and existing._session and existing._session.id == sessionId then
				existing._session = nil
			end
			return existing
		end)
	end)
	return ok
end

-- \u2500\u2500 Auto-save with heartbeat \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

function ${name}.setupAutoSave(player: Player, data: { [string]: any }, sessionId: string, intervalSeconds: number?)
	local interval = intervalSeconds or HEARTBEAT_INTERVAL
	activeSessions[player] = { data = data, sessionId = sessionId }

	local thread = task.spawn(function()
		while player.Parent do
			task.wait(interval)
			if not player.Parent then break end
			${name}.save(player, data, sessionId)
		end
	end)

	Players.PlayerRemoving:Connect(function(leavingPlayer)
		if leavingPlayer == player then
			activeSessions[player] = nil
			pcall(task.cancel, thread)
			${name}.save(player, data, sessionId)
			${name}.unlock(player, sessionId)
		end
	end)
end

-- BindToClose flushes every active session before the server shuts down. Skipped
-- in Studio test runs because game:BindToClose runs to completion (up to 30s)
-- on stop, which makes editor stops feel hung.
if not RunService:IsStudio() then
	game:BindToClose(function()
		for player, session in activeSessions do
			${name}.save(player, session.data, session.sessionId)
			${name}.unlock(player, session.sessionId)
		end
	end)
end

return ${name}
`;
}
function generateMigration(oldSchema, newSchema) {
  const oldFieldNames = new Set(flattenFieldNames(oldSchema.fields));
  const newFieldNames = new Set(flattenFieldNames(newSchema.fields));
  const added = [...newFieldNames].filter((n) => !oldFieldNames.has(n));
  const removed = [...oldFieldNames].filter((n) => !newFieldNames.has(n));
  const addedFields = added.map((path) => {
    const field = findField(newSchema.fields, path);
    if (!field) return "";
    return generateAddedFieldBlock(path, luauDefault(field));
  }).filter(Boolean);
  const removedFields = removed.map((path) => generateRemovedFieldBlock(path));
  return `-- Migration: ${oldSchema.name} v${oldSchema.version} \u2192 v${newSchema.version}
-- Generated by Luano DataStore Designer

local function migrate_${oldSchema.version}_to_${newSchema.version}(data)
${addedFields.join("\n\n") || "	-- \uCD94\uAC00\uB41C \uD544\uB4DC \uC5C6\uC74C"}

${removedFields.join("\n\n") || "	-- \uC81C\uAC70\uB41C \uD544\uB4DC \uC5C6\uC74C"}

	data._version = ${newSchema.version}
	return data
end

return migrate_${oldSchema.version}_to_${newSchema.version}
`;
}
function generateAddedFieldBlock(path, defaultExpr) {
  const parts = path.split(".");
  if (parts.length === 1) {
    return `	-- \uC0C8 \uD544\uB4DC \uCD94\uAC00: ${path}
	if data.${path} == nil then
		data.${path} = ${defaultExpr}
	end`;
  }
  const ancestorLines = [];
  for (let i = 0; i < parts.length - 1; i++) {
    const prefix = parts.slice(0, i + 1).join(".");
    ancestorLines.push(`	if data.${prefix} == nil then data.${prefix} = {} end`);
  }
  return `	-- \uC0C8 \uD544\uB4DC \uCD94\uAC00: ${path}
${ancestorLines.join("\n")}
	if data.${path} == nil then
		data.${path} = ${defaultExpr}
	end`;
}
function generateRemovedFieldBlock(path) {
  const parts = path.split(".");
  if (parts.length === 1) {
    return `	-- \uC81C\uAC70\uB41C \uD544\uB4DC: ${path}
	data.${path} = nil`;
  }
  const parentPath = parts.slice(0, -1).join(".");
  return `	-- \uC81C\uAC70\uB41C \uD544\uB4DC: ${path}
	if data.${parentPath} ~= nil then
		data.${path} = nil
	end`;
}
function flattenFieldNames(fields, prefix = "") {
  const names = [];
  for (const f of fields) {
    const fullName = prefix ? `${prefix}.${f.name}` : f.name;
    names.push(fullName);
    if (f.type === "table" && f.children) {
      names.push(...flattenFieldNames(f.children, fullName));
    }
  }
  return names;
}
function findField(fields, path) {
  const parts = path.split(".");
  let current = fields;
  let result = null;
  for (const part of parts) {
    result = null;
    for (const f of current) {
      if (f.name === part) {
        result = f;
        if (f.type === "table" && f.children) {
          current = f.children;
        }
        break;
      }
    }
    if (!result) return null;
  }
  return result;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  addSchema,
  deleteSchema,
  generateDataModule,
  generateMigration,
  loadSchemas,
  saveSchemas
});
