import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs"
import { join } from "path"

// ── Types ─────────────────────────────────────────────────────────────────────

export type FieldType =
  | "string" | "number" | "boolean"
  | "table" | "array"
  | "Instance" | "CFrame" | "Vector3" | "Color3"

export interface SchemaField {
  name: string
  type: FieldType
  default: unknown
  description?: string
  children?: SchemaField[] // type이 "table"일 때 하위 필드
}

export interface DataStoreSchema {
  name: string
  version: number
  description?: string
  fields: SchemaField[]
}

export interface SchemaFile {
  schemas: DataStoreSchema[]
  createdAt: string
  updatedAt: string
}

// ── 파일 경로 ──────────────────────────────────────────────────────────────────

function getSchemaPath(projectPath: string): string {
  return join(projectPath, ".luano", "datastore-schemas.json")
}

function ensureLuanoDir(projectPath: string): void {
  const dir = join(projectPath, ".luano")
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
}

// ── CRUD ──────────────────────────────────────────────────────────────────────

export function loadSchemas(projectPath: string): SchemaFile {
  const path = getSchemaPath(projectPath)
  if (!existsSync(path)) {
    return { schemas: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
  }
  try {
    return JSON.parse(readFileSync(path, "utf-8"))
  } catch {
    return { schemas: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
  }
}

export function saveSchemas(projectPath: string, file: SchemaFile): void {
  ensureLuanoDir(projectPath)
  file.updatedAt = new Date().toISOString()
  writeFileSync(getSchemaPath(projectPath), JSON.stringify(file, null, 2), "utf-8")
}

export function addSchema(projectPath: string, schema: DataStoreSchema): SchemaFile {
  const file = loadSchemas(projectPath)
  const existing = file.schemas.findIndex((s) => s.name === schema.name)
  if (existing >= 0) {
    file.schemas[existing] = schema
  } else {
    file.schemas.push(schema)
  }
  saveSchemas(projectPath, file)
  return file
}

export function deleteSchema(projectPath: string, name: string): SchemaFile {
  const file = loadSchemas(projectPath)
  file.schemas = file.schemas.filter((s) => s.name !== name)
  saveSchemas(projectPath, file)
  return file
}

// ── Luau 코드 생성 ─────────────────────────────────────────────────────────────

function luauDefault(field: SchemaField): string {
  if (field.default === null || field.default === undefined) {
    switch (field.type) {
      case "string": return '""'
      case "number": return "0"
      case "boolean": return "false"
      case "table": return "{}"
      case "array": return "{}"
      case "Vector3": return "Vector3.new(0, 0, 0)"
      case "Color3": return "Color3.new(1, 1, 1)"
      case "CFrame": return "CFrame.new()"
      default: return "nil"
    }
  }
  if (typeof field.default === "string") return `"${field.default}"`
  if (typeof field.default === "boolean") return field.default ? "true" : "false"
  return String(field.default)
}

function generateFieldTemplate(fields: SchemaField[], indent: number): string {
  const pad = "\t".repeat(indent)
  const lines: string[] = []
  for (const f of fields) {
    const comment = f.description ? ` -- ${f.description}` : ""
    if (f.type === "table" && f.children?.length) {
      lines.push(`${pad}${f.name} = {${comment}`)
      lines.push(generateFieldTemplate(f.children, indent + 1))
      lines.push(`${pad}},`)
    } else {
      lines.push(`${pad}${f.name} = ${luauDefault(f)},${comment}`)
    }
  }
  return lines.join("\n")
}

export function generateDataModule(schema: DataStoreSchema): string {
  const template = generateFieldTemplate(schema.fields, 2)

  return `--!strict
-- Auto-generated by Luano DataStore Designer
-- Schema: ${schema.name} v${schema.version}
-- ${new Date().toISOString()}

local DataStoreService = game:GetService("DataStoreService")
local Players = game:GetService("Players")

local ${schema.name} = {}
${schema.name}.__index = ${schema.name}

local DATA_STORE_NAME = "${schema.name}"
local DATA_VERSION = ${schema.version}

local store = DataStoreService:GetDataStore(DATA_STORE_NAME)

-- 기본 데이터 템플릿
function ${schema.name}.getTemplate(): { [string]: any }
\treturn {
\t\t_version = DATA_VERSION,
${template}
\t}
end

-- 데이터 로드 (없으면 템플릿 생성)
function ${schema.name}.load(player: Player): { [string]: any }
\tlocal key = "player_" .. player.UserId
\tlocal success, data = pcall(function()
\t\treturn store:GetAsync(key)
\tend)

\tif not success or not data then
\t\tdata = ${schema.name}.getTemplate()
\tend

\t-- 버전 마이그레이션
\tif (data._version or 0) < DATA_VERSION then
\t\tdata = ${schema.name}.migrate(data, data._version or 0)
\tend

\treturn data
end

-- 데이터 저장
function ${schema.name}.save(player: Player, data: { [string]: any }): boolean
\tlocal key = "player_" .. player.UserId
\tlocal success, err = pcall(function()
\t\tstore:SetAsync(key, data)
\tend)

\tif not success then
\t\twarn("[${schema.name}] Save failed for " .. player.Name .. ": " .. tostring(err))
\tend
\treturn success
end

-- 버전 마이그레이션
function ${schema.name}.migrate(data: { [string]: any }, fromVersion: number): { [string]: any }
\tlocal template = ${schema.name}.getTemplate()

\t-- 새 필드 추가 (기존 데이터 보존)
\tfor key, defaultValue in template do
\t\tif data[key] == nil then
\t\t\tdata[key] = defaultValue
\t\tend
\tend

\tdata._version = DATA_VERSION
\treturn data
end

-- 자동 저장 설정
function ${schema.name}.setupAutoSave(player: Player, data: { [string]: any }, intervalSeconds: number?)
\tlocal interval = intervalSeconds or 60

\ttask.spawn(function()
\t\twhile player.Parent do
\t\t\ttask.wait(interval)
\t\t\t${schema.name}.save(player, data)
\t\tend
\tend)

\t-- 퇴장 시 저장
\tPlayers.PlayerRemoving:Connect(function(leavingPlayer)
\t\tif leavingPlayer == player then
\t\t\t${schema.name}.save(player, data)
\t\tend
\tend)
end

return ${schema.name}
`
}

// ── 마이그레이션 코드 생성 ────────────────────────────────────────────────────

export function generateMigration(
  oldSchema: DataStoreSchema,
  newSchema: DataStoreSchema
): string {
  const oldFieldNames = new Set(flattenFieldNames(oldSchema.fields))
  const newFieldNames = new Set(flattenFieldNames(newSchema.fields))

  const added = [...newFieldNames].filter((n) => !oldFieldNames.has(n))
  const removed = [...oldFieldNames].filter((n) => !newFieldNames.has(n))

  const addedFields = added.map((name) => {
    const field = findField(newSchema.fields, name)
    return field ? `\t-- 새 필드 추가: ${name}\n\tif data.${name} == nil then\n\t\tdata.${name} = ${luauDefault(field)}\n\tend` : ""
  }).filter(Boolean)

  const removedFields = removed.map((name) => {
    return `\t-- 제거된 필드: ${name}\n\tdata.${name} = nil`
  })

  return `-- Migration: ${oldSchema.name} v${oldSchema.version} → v${newSchema.version}
-- Generated by Luano DataStore Designer

local function migrate_${oldSchema.version}_to_${newSchema.version}(data)
${addedFields.join("\n\n") || "\t-- 추가된 필드 없음"}

${removedFields.join("\n\n") || "\t-- 제거된 필드 없음"}

\tdata._version = ${newSchema.version}
\treturn data
end

return migrate_${oldSchema.version}_to_${newSchema.version}
`
}

function flattenFieldNames(fields: SchemaField[], prefix = ""): string[] {
  const names: string[] = []
  for (const f of fields) {
    const fullName = prefix ? `${prefix}.${f.name}` : f.name
    names.push(fullName)
    if (f.type === "table" && f.children) {
      names.push(...flattenFieldNames(f.children, fullName))
    }
  }
  return names
}

function findField(fields: SchemaField[], name: string): SchemaField | null {
  for (const f of fields) {
    if (f.name === name) return f
    if (f.type === "table" && f.children) {
      const found = findField(f.children, name)
      if (found) return found
    }
  }
  return null
}
